'use strict';
function clamp(x,lo,hi){return Math.max(lo,Math.min(hi,x));}
function mean(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:null;}
function realizedAnnualizedReturn(startPrice,currentPrice,days){if(!(startPrice>0)||!(currentPrice>0)||!(days>=90))return null;return Math.pow(currentPrice/startPrice,365/days)-1;}
function groupStats(obs,key,field){const out={};for(const o of obs)(out[o[key]||'unknown']||=[]).push(o[field]);return Object.fromEntries(Object.entries(out).map(([k,v])=>[k,{observations:v.length,bias:mean(v),adjustment:v.length>=6?clamp(mean(v)*0.30,-0.06,0.05):0}]));}
function buildCalibration(history,currentByTicker,now=new Date()){
 const returns=[], forecasts=[], methods=[];
 for(const snap of history?.snapshots||[]){const ageDays=(now-new Date(snap.date))/86400000;if(ageDays<270)continue;
  for(const old of snap.stocks||[]){const cur=currentByTicker.get(old.ticker);if(!cur)continue;const industry=old.industry||'unknown',category=old.category||'Unknown';
   const realized=realizedAnnualizedReturn(old.price,cur.price?.current,ageDays);if(Number.isFinite(realized)&&Number.isFinite(old.expectedCAGR))returns.push({industry,category,error:realized-old.expectedCAGR});
   const currentRevenue=cur.financials?.years?.at(-1)?.revenue; if(old.baseRevenue>0&&currentRevenue>0&&ageDays>=300){const actual=Math.pow(currentRevenue/old.baseRevenue,365/ageDays)-1; if(Number.isFinite(old.forecastGrowth)) forecasts.push({industry,category,ownError:actual-old.forecastGrowth,analystError:Number.isFinite(old.analystGrowth)?actual-old.analystGrowth:null,historyError:Number.isFinite(old.historicalGrowth)?actual-old.historicalGrowth:null});}
   if(ageDays>=300&&old.methodFairValues&&cur.price?.current>0){for(const [method,fv] of Object.entries(old.methodFairValues)){if(fv>0)methods.push({industry,category,method,error:Math.abs(cur.price.current-fv)/cur.price.current});}}
  }
 }
 const retOverall=mean(returns.map(o=>o.error));
 const forecastOverall={observations:forecasts.length,ownBias:mean(forecasts.map(o=>o.ownError).filter(Number.isFinite))||0,analystBias:mean(forecasts.map(o=>o.analystError).filter(Number.isFinite))||0,historyBias:mean(forecasts.map(o=>o.historyError).filter(Number.isFinite))||0};
 const forecastByIndustry={};for(const i of new Set(forecasts.map(o=>o.industry))){const a=forecasts.filter(o=>o.industry===i);forecastByIndustry[i]={observations:a.length,ownBias:a.length>=5?clamp(mean(a.map(o=>o.ownError).filter(Number.isFinite))||0,-.08,.08):0,analystBias:a.length>=5?clamp(mean(a.map(o=>o.analystError).filter(Number.isFinite))||0,-.08,.08):0,historyBias:a.length>=5?clamp(mean(a.map(o=>o.historyError).filter(Number.isFinite))||0,-.08,.08):0};}
 const methodAccuracy={};for(const i of new Set(methods.map(o=>o.industry))){methodAccuracy[i]={};for(const m of new Set(methods.filter(o=>o.industry===i).map(o=>o.method))){const a=methods.filter(o=>o.industry===i&&o.method===m).map(o=>o.error);methodAccuracy[i][m]={observations:a.length,mae:mean(a),multiplier:a.length>=5?clamp(1/(0.45+(mean(a)||.55)),0.65,1.35):1};}}
 return {generatedAt:now.toISOString(),observationCount:returns.length,isCalibrated:returns.length>=25,overall:{observations:returns.length,bias:retOverall,adjustment:returns.length>=25?clamp(retOverall*.25,-.05,.03):0},byCategory:groupStats(returns,'category','error'),byIndustry:groupStats(returns,'industry','error'),forecastOverall,forecastByIndustry,methodAccuracy};
}
function applyCalibration(profile,stock,calibration){if(!profile||!Number.isFinite(profile.expectedCAGR))return{...profile,calibrationAdjustment:0};const industry=stock.valuation?.industryModel?.model||'unknown',category=stock.valuation?.category||stock.category||'Unknown';const adjustment=clamp((calibration?.byIndustry?.[industry]?.adjustment||0)*.5+(calibration?.byCategory?.[category]?.adjustment||0)*.3+(calibration?.overall?.adjustment||0)*.2,-.06,.04);return{...profile,uncalibratedExpectedCAGR:profile.expectedCAGR,uncalibratedRiskAdjustedCAGR:profile.riskAdjustedCAGR,expectedCAGR:clamp(profile.expectedCAGR+adjustment,-.6,1),riskAdjustedCAGR:Number.isFinite(profile.riskAdjustedCAGR)?clamp(profile.riskAdjustedCAGR+adjustment,-.6,1):null,calibrationAdjustment:adjustment,calibrationObservationCount:calibration?.observationCount||0,calibrationActive:!!calibration?.isCalibrated};}
module.exports={buildCalibration,applyCalibration,realizedAnnualizedReturn};
