'use strict';
const fs=require('fs'); const path=require('path');
function config(){const url=String(process.env.SUPABASE_URL||'').trim().replace(/\/+$/,'').replace(/\/rest\/v1$/,'');const key=String(process.env.SUPABASE_SERVICE_KEY||'').trim();if(!url||!key)throw new Error('SUPABASE_URL and SUPABASE_SERVICE_KEY are required.');return{url,key};}
async function get(table,params){const{url,key}=config();const endpoint=new URL(`${url}/rest/v1/${table}`);for(const[k,v]of Object.entries(params||{}))endpoint.searchParams.set(k,v);const r=await fetch(endpoint,{headers:{apikey:key,Authorization:`Bearer ${key}`}});if(!r.ok)throw new Error(`${table}: ${r.status} ${await r.text()}`);return r.json();}
function mean(v){const x=v.filter(Number.isFinite);return x.length?x.reduce((a,b)=>a+b,0)/x.length:null;} function median(v){const x=v.filter(Number.isFinite).sort((a,b)=>a-b);if(!x.length)return null;const i=Math.floor(x.length/2);return x.length%2?x[i]:(x[i-1]+x[i])/2;}
function corr(a,b){const p=a.map((x,i)=>[x,b[i]]).filter(([x,y])=>Number.isFinite(x)&&Number.isFinite(y));if(p.length<3)return null;const mx=mean(p.map(x=>x[0])),my=mean(p.map(x=>x[1]));const n=p.reduce((s,[x,y])=>s+(x-mx)*(y-my),0),dx=Math.sqrt(p.reduce((s,[x])=>s+(x-mx)**2,0)),dy=Math.sqrt(p.reduce((s,[,y])=>s+(y-my)**2,0));return dx&&dy?n/(dx*dy):null;}
function summarize(rows){const e=rows.map(r=>Number(r.expected_cagr)),a=rows.map(r=>Number(r.realized_cagr)),spy=rows.map(r=>Number(r.realized_alpha)),qqq=rows.map(r=>Number(r.alpha_vs_qqq));const err=a.map((x,i)=>x-e[i]);return{observations:rows.length,predictedMean:mean(e),realizedMean:mean(a),medianRealized:median(a),bias:mean(err),mae:mean(err.map(Math.abs)),rmse:Math.sqrt(mean(err.map(x=>x*x))||0),correlation:corr(e,a),positiveRate:mean(a.map(x=>x>0?1:0)),beatSPYRate:mean(spy.map(x=>x>0?1:0)),beatQQQRate:mean(qqq.filter(Number.isFinite).map(x=>x>0?1:0)),averageAlphaVsSPY:mean(spy),averageAlphaVsQQQ:mean(qqq)};}
function group(rows,key){const out={};for(const v of [...new Set(rows.map(r=>r[key]||'Unknown'))])out[v]=summarize(rows.filter(r=>(r[key]||'Unknown')===v));return out;}
function buckets(rows){const defs=[[-Infinity,.05,'<5%'],[.05,.10,'5-10%'],[.10,.15,'10-15%'],[.15,.20,'15-20%'],[.20,Infinity,'20%+']];const out={};for(const[lo,hi,name]of defs)out[name]=summarize(rows.filter(r=>Number(r.expected_cagr)>=lo&&Number(r.expected_cagr)<hi));return out;}
async function main(){const rows=await get('prediction_outcomes',{select:'*',order:'snapshot_date.asc',limit:'100000'});const mature=rows.filter(r=>Number.isFinite(Number(r.realized_cagr)));const byHorizon={};for(const h of [...new Set(mature.map(r=>r.horizon_months))].sort((a,b)=>a-b)){const x=mature.filter(r=>r.horizon_months===h);byHorizon[`${h}m`]={overall:summarize(x),byRating:group(x,'rating'),byCategory:group(x,'category'),byIndustry:group(x,'industry'),byEngineVersion:group(x,'engine_version'),expectedReturnBuckets:buckets(x)};}
const report={generatedAt:new Date().toISOString(),status:mature.length>=100?'active':'collecting-history',minimumRecommendedObservations:100,totalObservations:mature.length,byHorizon};const out=path.join(__dirname,'..','data','calibration-dashboard.json');fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,JSON.stringify(report,null,2));console.log(JSON.stringify({status:report.status,totalObservations:report.totalObservations,horizons:Object.keys(byHorizon)},null,2));}
main().catch(e=>{console.error(e);process.exit(1);});
